spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      jpa:
        properties:
          hibernate:
            default_schema: player_data
    datasource:
      initialization-mode: always
      url: jdbc:h2:mem:testdb;
      driver-class-name: org.h2.Driver
      username: sa
      password:

server:
  port: 8081

logging:
  level:
    root: info
    org.nenad.paunov: debug
    com.zaxxer.hikari: info
    org.hibernate: info
    org.springframework: info
    io.lettuce: info
    io.netty: info

player_service_host: http://localhost:8080/